package:
  name: nlopt
  version: 2.7.0

source:
  url: https://github.com/stevengj/nlopt/archive/v2.7.0.tar.gz
  sha256: b881cc2a5face5139f1c5a30caf26b7d3cb43d69d5e423c9d78392f99844499f

  extras:
    -
      - src/setup.py
      - ./setup.py
    -
      - src/MANIFEST.in
      - ./MANIFEST.in

requirements:
  run:
    - numpy

build:
  script: |
    mkdir nlopt
    mkdir build
    cd build
    emcmake cmake \
       -LAH \
       -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../nlopt \
       -DNLOPT_GUILE=OFF \
       -DNLOPT_MATLAB=OFF \
       -DNLOPT_OCTAVE=OFF \
       ..
    emmake make -j ${PYODIDE_JOBS:-3}
    make install
    cp ./src/swig/nlopt.py ../nlopt/

test:
  imports:
    - nlopt
